# Generated by Django 5.0.1 on 2024-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementsRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=25, null=True)),
                ('write_off', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=25, null=True)),
                ('purpose_of_payment', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('contractor', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('doc_number', models.IntegerField()),
                ('transaction_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('division', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('article_revenue', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
